### PR TITLE
Update circlator yaml

### PR DESCRIPTION
**Pull request by sternp**
Spades 3.7.1 is recommended as it gives better results

### CODE REVIEW

**Comment by rhysnewell** [comment]
Happy to update this, but do you have a source for this? What do they mean by better? Just want to make sure before regressing so many updates

**Comment by sternp** [comment]
You are greeted by the following message when circlator launches:

`WARNING: SPAdes version 3.9.0 is being used. It will work, but better results are usually obtained from Circlator using SPAdes version 3.7.1. Although 3.7.1 is not the latest version, we recommend it for Circlator.`

**Comment by rhysnewell** [comment]
Lol, true. I still wonder what they mean by better, happy to merge this.

**Comment by sternp** [comment]
Okay - so 3.7.1 isn't available in conda.

Also, apparently (https://github.com/sanger-pathogens/circlator/issues/72) the 'improved' performance might be a result of misassemblies. 

For these two reasons can you revert this back to spades 3.9.0. Sorry for this!

**Comment by rhysnewell** [comment]
Yeah, the misassemblies was what I was thinking... A lot of the time older versions of assemblers seem to perform better than newer versions, but it is just the result of misassemblies creating larger contigs

**Pull request merged**
