### PR TITLE
Implement skip abundances arg

### PR DESCRIPTION
**Pull request by AroneyS**
Add argument to recover to skip CoverM abundances post-binning.
Last unskippable rule that isn't necessary for large-scale binning efforts.

- [x] Tested in dryrun
- [x] Tested manually in test_integration.py
- [x] Tested manually with real samples

### CODE REVIEW

**Comment by AroneyS** [comment]
Can we have another release after this? I'll add the new release onto bioconda.

**Comment by AroneyS** [comment]
I also noticed that semibin isn't respecting the threads parameter.

**Review by rhysnewell — APPROVED** [review]

**Comment by rhysnewell** [comment]
> I also noticed that semibin isn't respecting the threads parameter.

This is likely a problem with semibin itself, not sure we can control it unless we manually set some environment variables before semibin runs

**Comment by AroneyS** [comment]
> > I also noticed that semibin isn't respecting the threads parameter.
> 
> This is likely a problem with semibin itself, not sure we can control it unless we manually set some environment variables before semibin runs

Yeh, I'll look more into it and raise an issue on their end. Pretty sure we are calling it correctly.

**Pull request merged**
