### PR TITLE
Merge Dev into Main

### PR DESCRIPTION
**Pull request by rhysnewell**
Updates main to contain the latest set of fixes as well as medaka polishing when using nanopore reads

### CODE REVIEW

**Comment by rhysnewell** [comment]
@wwood or @sternp You may want review this so it can be pushed through

**Review by sternp — APPROVED** [review]

**Comment by rhysnewell** [comment]
Still blocked

**Review by wwood — APPROVED** [review]

**Comment by AroneyS** [comment]
@rhysnewell are you going to do a new release?

**Comment by sternp** [comment]
A new release would be good  :)

**Comment by rhysnewell** [comment]
Should be done, v0.6.0 I think it mostly released correctly. The changelog got messed up though, I don't know why that keeps happening

**Pull request merged**
