### PR TITLE
fix: removal of instances of shell=True

### PR DESCRIPTION
**Pull request by rhysnewell**
Replacing all instances of `shell=True` when using subprocess calls.
Many instances can be converted to more pythonic methods using `shutil` or `os`, others involve dealing with pipes between between subprocesses. Work is ongoing on these

### CODE REVIEW

**Comment by rhysnewell** [comment]
It would be good if we could just throw this PR against a few actual samples and check to see if any of the steps fail

**Comment by AroneyS** [comment]
I get the following error running `test_integration.py`. Something to do with quoting the default resources?

```python
08/09/2023 08:29:48 AM INFO: Time - 08:29:48 09-08-2023
08/09/2023 08:29:48 AM INFO: Command - /home/aroneys/m/users/aroneys/.conda/envs/aviary_dev/bin/aviary recover --assembly /mnt/hpccs01/scratch/microbiome/aroneys/src/aviary/test/data/assembly.fasta -o /data1/tmp/tmpal4dqznp/aviary_out -1 /mnt/hpccs01/scratch/microbiome/aroneys/src/aviary/test/data/wgsim.1.fq.gz -2 /mnt/hpccs01/scratch/microbiome/aroneys/src/aviary/test/data/wgsim.2.fq.gz --skip-binners concoct rosella vamb metabat maxbin --refinery-max-iterations 1 --conda-prefix /home/aroneys/m/users/aroneys/.conda/envs -n 32 -t 32
08/09/2023 08:29:48 AM INFO: Version - 0.6.0
08/09/2023 08:29:48 AM INFO: Configuration file written to /data1/tmp/tmpal4dqznp/aviary_out/config.yaml
08/09/2023 08:29:48 AM INFO: Executing: snakemake --snakefile /mnt/hpccs01/scratch/microbiome/aroneys/src/aviary/aviary/modules/Snakefile --directory /data1/tmp/tmpal4dqznp/aviary_out --cores 32 --rerun-incomplete   --configfile /data1/tmp/tmpal4dqznp/aviary_out/config.yaml --nolock  --conda-frontend mamba --default-resources "tmpdir='/data1/tmp'" --resources mem_mb=256000   --use-conda --conda-prefix /home/aroneys/m/users/aroneys/.conda/envs   recover_mags
Resource definition must start with a valid identifier, but found "tmpdir.
```

**Comment by rhysnewell** [comment]
Okay, should be good to go now. Tested `recover` and `assemble` with short reads but long read pipeline should also be run to check for bugs

**Comment by AroneyS** [comment]
I added a long-reads integration test (for running manually). It fails at rule polish_metagenome_flye with error:

```python
Traceback (most recent call last):
  File "/data1/tmp/tmpmfps_hyl/aviary_out/.snakemake/scripts/tmptlcg50v5.polish.py", line 343, in <module>
    run_polish(
TypeError: run_polish() got an unexpected keyword argument 'output_fasta'
```

**Comment by rhysnewell** [comment]
Cleaned up some racon bugs that had slipped in when doing reference filtering, longread pipeline works as intended and feeds into recovery pipeline cleanly. Seems to run well on my end

**Review by AroneyS — CHANGES_REQUESTED** [review]
All integration tests now complete successfully.
I think everything that was changed is at least run by the integration tests, except for `run_lorikeet.py`, `process_batch.py` and `process_viral_batch.py`

**Comment by rhysnewell** [comment]
I think there are some scripts and rules that are only hit when a reference filter is provided, but they can be pretty easily tested by just providing a dummy fasta file and they all pass

**Review by AroneyS — APPROVED** [review]

**Pull request merged**
