### PR TITLE
Citations update

### PR DESCRIPTION
**Pull request by wwood**
Had to go through this process myself, so added some info to make it easier.

The more challenging thing here is that it would be nice to know what versions of software were used, but that isn't specified in the conda envs as they are mostly open-ended.

WDYT about making each tool create a JSON file which includes metadata like the version of the software used (and e.g. the CheckM2 DB version used), and then providing a summarised version of those files as an output, so a user knows what tools were used?

Also why is GraftM in the list?

### CODE REVIEW

**Comment by wwood** [comment]
I changed the citation from spades to metaspades, but do we need both?

**Comment by wwood** [comment]
@AroneyS thoughts?

**Comment by AroneyS** [comment]
> WDYT about making each tool create a JSON file which includes metadata like the version of the software used (and e.g. the CheckM2 DB version used), and then providing a summarised version of those files as an output, so a user knows what tools were used?

Sounds like a good idea. An extra module with a rule for each environment? Could be a lot of work depending how well-organised each software is.

Would we add the json as an input to the main invocation of each software so they are only logged if its run?

CheckM2 DB version should be logged by CheckM2 too though, right?

**Comment by rhysnewell** [comment]
> Also why is GraftM in the list?

Is GraftM not used by singleM? I think I included it lieu of a singleM citation

> WDYT about making each tool create a JSON file which includes metadata like the version of the software used (and e.g. the CheckM2 DB version used), and then providing a summarised version of those files as an output, so a user knows what tools were used?

We could probably set it up so `mamba list` is run each time a rule that utilised a conda environment is run. This could output to a file in a new folder (`versions/`) that users could refer to when searching for what software version was run. Shouldn't be too hard, just would take time setting it up for each rule.

**Review by rhysnewell — APPROVED** [review]

**Comment by rhysnewell** [comment]
ah damn that went into main.

**Comment by wwood** [comment]
sorry - I actually remembered but didn't get around to deleting the PR, then making another. I wonder if there's a way to set a default merge branch.

Techincally the docs are now wrong as I changed semibin to v2, but eh.

**Comment by AroneyS** [comment]
Change the default branch to dev? Though I think that changes the initial branch that people view

**Comment by rhysnewell** [comment]
Yeah, changes the cloning and viewing branch. Also probably messes with any automated processes or which branch is used for version releases so maybe not the best idea

**Pull request merged**
