### PR TITLE
bump to v0.8.0

### PR DESCRIPTION
**Pull request by rhysnewell**
I think we've had a lot of movement recent which is probably due for a version bump.
Thinking there have been enough changes that make it no longer in the realm of v0.7.X as many of them would result in compatibility issues.

Otherwise, I can delete this and just change it to v0.7.4

### CODE REVIEW

**Comment by AroneyS** [comment]
https://github.com/rhysnewell/aviary/pull/127 - fix skip-abundances
https://github.com/rhysnewell/aviary/pull/129 - better snakemake cluster support
https://github.com/rhysnewell/aviary/pull/131 - update snakemake version
https://github.com/rhysnewell/aviary/pull/132 - temp for long-read qc
https://github.com/rhysnewell/aviary/pull/139 - read qc improvements

I think a v0.8.0 is warranted. The snakemake resources does change threads for many rules and adds rerun-triggers mtime by default.

**Comment by rhysnewell** [comment]
I'll add a fix to those unit tests in this PR, hold up

**Comment by rhysnewell** [comment]
@AroneyS, I don't know if you want to double check the tests on your end

**Comment by AroneyS** [comment]
Yep. Running test_long_read_recovery now. Takes ~40mins for me.

**Review by AroneyS — APPROVED** [review]
test_long_read_recovery passes

**Pull request merged**
