### PR TITLE
Switch memory multiplier to 1000

### PR DESCRIPTION
**Pull request by AroneyS**

### CODE REVIEW

**Comment by wwood** [comment]
Not saying I disagree, but what is the point of this?

**Comment by rhysnewell** [comment]
I'm not sure I do agree with this change. Why do you want this? I am aware that technically 1 GB should be 1000 MB by IEC standards, but I'm pretty sure most people would expect 1 GB to 1024 MB as that is the (de facto) standard used when talking about RAM (https://en.wikipedia.org/wiki/Byte#Units_based_on_powers_of_2)

**Comment by AroneyS** [comment]
I guess we could change this instead: https://github.com/centre-for-microbiome-research/hpc_scripts/blob/1a0a25457edaae792e4175592ddac5236bd9b840/bin/snakemake_mqsub#L84

Its just that job submission through Aviary, snakemake and mqsub increases the RAM request by `*1024` and then `/1000`. I thought it was snakemake doing the conversion but its actually our script...

**Comment by wwood** [comment]
Annoying.

The reason for snakemake_mqsub is doing that is because it was following on from the open nodes have 1000G of RAM, not 1024G, after rounding due to the OS taking up RAM itself I think - https://github.com/centre-for-microbiome-research/hpc_scripts/blob/1a0a25457edaae792e4175592ddac5236bd9b840/bin/mqsub#L432

I think we should change snakemake_mqsub, and not aviary - agree @AroneyS  ?

**Pull request closed without merging**
