### PR TITLE
attempt to fix #166 by interleaving reads correctly

### LINKED ISSUE #166: Skip QC produces concatenated (not interleaved) short-reads
Short forward+reverse reads are concatenated in sequence instead of interleaved (expected by metaspades and megahit)
https://github.com/rhysnewell/aviary/blob/5915015b114ef7284a3e50d559e204b4b6c5428d/aviary/modules/quality_control/scripts/qc_short_reads.py#L89

Please tell me I'm wrong...

### PR DESCRIPTION
**Pull request by rhysnewell**
minor fixes from #163 and major fix for #166 
Version updates for #165

### CODE REVIEW

**Comment by AroneyS** [comment]
Still running some tests. Added `gzip.open` to write in gz. pigz would be faster, but I'm not sure how to do that with append.

**Comment by rhysnewell** [comment]
I had been thinking about this, I think the best option would be to append all reads to a non-compressed file and then use pigz at the end to compress the output and make sure the uncompressed file is deleted. Would give the best compression and likely be faster

**Comment by AroneyS** [comment]
Yeh that makes sense. Do you have time now or should I give it a go?

**Comment by rhysnewell** [comment]
I won't have time until later today

**Review by AroneyS — APPROVED** [review]
Would prefer some tests that run interleave and check output

**Comment by rhysnewell** [comment]
@AroneyS Any further commits incoming or ready to merge?

**Comment by AroneyS** [comment]
I think its ready.

**Pull request merged**
