### PR TITLE
assemble/recover: Require users to specify coassembly or not.

### LINKED ISSUE #219: --no-coassembly flag?
Hey,

I reckon it is a little anti-intuitive that when multiple readsets are specified, that only the first is used for assembly by default.

WDYT about requiring users to explicitly use `--coassemble` or a new flag `--no-coassembly` for `recover` when no input assembly is given, otherwise erroring out? Just lost a day's compute time because I mistakenly didn't (modified the wrong script).

Thanks.

### PR DESCRIPTION
**Pull request by wwood**
Fixes #219.

This is a breaking change for the command line (before it would silently not coassemble), but the break will cause an error to be thrown at least. I guess there are documention fixes to be done too.

### CODE REVIEW

**Comment by AroneyS** [comment]
Integration test pass. I also checked with a dryrun and it seems to be working as expected.

@rhysnewell can you make a new release once this and https://github.com/rhysnewell/aviary/pull/222 are merged?

**Review by AroneyS — APPROVED** [review]

**Comment by wwood** [comment]
Thoughts @rhysnewell ? Wanting to check since this is a breaking change

**Comment by rhysnewell** [comment]
@wwood I was waiting for clarification of my comment earlier. What's the default behaviour now?

**Comment by wwood** [comment]
Previously it would silently just assemble the first, now it errors out unless one of the flags is set

**Comment by rhysnewell** [comment]
@wwood and what if only a single set of reads is supplied? Does the user still have to add the flag?

**Comment by wwood** [comment]
No, it just works as you'd expect - the 1 readset is used and no flag is necessary

**Comment by rhysnewell** [comment]
Okay, that sounds all good then. Any other PRs you want before the next release?

**Pull request merged**
