### PR TITLE
citations: Improve them.

### PR DESCRIPTION
**Pull request by wwood**

### CODE REVIEW

**Review by rhysnewell — CHANGES_REQUESTED** [review]
Add Sam as an author to aviary, probably a few others need to be added as well.

Also, I think you forgot my name on the lorikeet citation 🥲

**Comment by rhysnewell** [comment]
The coverm author order looks a bit weird to me should it not be something more like:
**CoverM**: Woodcroft B.J., Newell. R.J.P., Aroney S., Nissen J., Carmago A., Tyson G. W.  Available at https://github.com/wwood/CoverM

**Comment by wwood** [comment]
OK. The specific order of authors that paper still in flux. Let's call it

>CoverM: Read mapping statistics for metagenomics

as a title too.

**Comment by AroneyS** [comment]
@wwood So are we leaving the author list as-is for now?

**Comment by wwood** [comment]
Do you mind changing to Rhys' plus title change? As I say, in flux

**Review by rhysnewell — APPROVED** [review]

**Pull request merged**
